package org.bildit.model.hibernate;
// Generated Apr 1, 2021 11:45:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="CONTACT"
    ,schema="dbo"
    ,catalog="newDB"
)
public class Contact  implements java.io.Serializable {


     private int id;
     private String firstname;
     private String lastname;
     private String phonenumber;
     private String address;
     private String email;
     private Integer userid;

    public Contact() {
    }

	
    public Contact(int id) {
        this.id = id;
    }
    public Contact(int id, String firstname, String lastname, String phonenumber, String address, String email, Integer userid) {
       this.id = id;
       this.firstname = firstname;
       this.lastname = lastname;
       this.phonenumber = phonenumber;
       this.address = address;
       this.email = email;
       this.userid = userid;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="FIRSTNAME", length=50)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="LASTNAME", length=50)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="PHONENUMBER", length=50)
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    
    @Column(name="ADDRESS", length=50)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="USERID")
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }




}


